/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerAccountSession } from './careworker-account-session';

/**
 * 
 * @export
 * @interface CareworkerBatchUpdateAccountSessionsRequest
 */
export interface CareworkerBatchUpdateAccountSessionsRequest {
    /**
     * The AccountSession resource which replaces the resource on the server.
     * @type {Array<CareworkerAccountSession>}
     * @memberof CareworkerBatchUpdateAccountSessionsRequest
     */
    accountSessions?: Array<CareworkerAccountSession>;
    /**
     * 
     * @type {string}
     * @memberof CareworkerBatchUpdateAccountSessionsRequest
     */
    updateMask?: string;
}


