/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerDepartment } from './careworker-department';

/**
 * 
 * @export
 * @interface CareworkerBed
 */
export interface CareworkerBed {
    /**
     * 
     * @type {string}
     * @memberof CareworkerBed
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerBed
     */
    tenantId?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerBed
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerBed
     */
    departmentId?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerBed
     */
    remark?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CareworkerBed
     */
    status?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CareworkerBed
     */
    createAt?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerBed
     */
    updateAt?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerBed
     */
    deleteAt?: number;
    /**
     * 
     * @type {CareworkerDepartment}
     * @memberof CareworkerBed
     */
    department?: CareworkerDepartment;
}


