/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CareworkerAccountSession
 */
export interface CareworkerAccountSession {
    /**
     * 
     * @type {string}
     * @memberof CareworkerAccountSession
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof CareworkerAccountSession
     */
    accountId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CareworkerAccountSession
     */
    terminal?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CareworkerAccountSession
     */
    token?: string;
    /**
     * 
     * @type {number}
     * @memberof CareworkerAccountSession
     */
    updateTime?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerAccountSession
     */
    expireTime?: number;
}


