/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CareworkerDictType
 */
export interface CareworkerDictType {
    /**
     * 
     * @type {string}
     * @memberof CareworkerDictType
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerDictType
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerDictType
     */
    type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CareworkerDictType
     */
    status?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CareworkerDictType
     */
    remark?: string;
    /**
     * 
     * @type {number}
     * @memberof CareworkerDictType
     */
    createAt?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerDictType
     */
    updateAt?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerDictType
     */
    deleteAt?: number;
}


