/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerNoticeRecord } from './careworker-notice-record';

/**
 * 
 * @export
 * @interface CareworkerBatchUpdateNoticeRecordsRequest
 */
export interface CareworkerBatchUpdateNoticeRecordsRequest {
    /**
     * The NoticeRecord resource which replaces the resource on the server.
     * @type {Array<CareworkerNoticeRecord>}
     * @memberof CareworkerBatchUpdateNoticeRecordsRequest
     */
    noticeRecords?: Array<CareworkerNoticeRecord>;
    /**
     * 
     * @type {string}
     * @memberof CareworkerBatchUpdateNoticeRecordsRequest
     */
    updateMask?: string;
}


