/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerSmsLog } from './careworker-sms-log';

/**
 * 
 * @export
 * @interface CareworkerBatchCreateSmsLogsRequest
 */
export interface CareworkerBatchCreateSmsLogsRequest {
    /**
     * The parent resource name where the SmsLog is to be created.
     * @type {string}
     * @memberof CareworkerBatchCreateSmsLogsRequest
     */
    parent?: string;
    /**
     * The SmsLog resource to create. The field name should match the Noun in the method name.
     * @type {Array<CareworkerSmsLog>}
     * @memberof CareworkerBatchCreateSmsLogsRequest
     */
    smsLogs?: Array<CareworkerSmsLog>;
}


