/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerDictType } from './careworker-dict-type';

/**
 * 
 * @export
 * @interface CareworkerListDictTypesResponse
 */
export interface CareworkerListDictTypesResponse {
    /**
     * The field name should match the noun \"DictType\" in the method name. There will be a maximum number of items returned based on the page_size field in the request.
     * @type {Array<CareworkerDictType>}
     * @memberof CareworkerListDictTypesResponse
     */
    dictTypes?: Array<CareworkerDictType>;
    /**
     * Token to retrieve the next page of results, or empty if there are no more results in the list.
     * @type {string}
     * @memberof CareworkerListDictTypesResponse
     */
    nextPageToken?: string;
}


