/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerRoleMenu } from './careworker-role-menu';

/**
 * 
 * @export
 * @interface CareworkerBatchCreateRoleMenusRequest
 */
export interface CareworkerBatchCreateRoleMenusRequest {
    /**
     * The parent resource name where the RoleMenu is to be created.
     * @type {string}
     * @memberof CareworkerBatchCreateRoleMenusRequest
     */
    parent?: string;
    /**
     * The RoleMenu resource to create. The field name should match the Noun in the method name.
     * @type {Array<CareworkerRoleMenu>}
     * @memberof CareworkerBatchCreateRoleMenusRequest
     */
    roleMenus?: Array<CareworkerRoleMenu>;
}


