/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerBatchGetEmployeesByTenantIdRequestView } from './careworker-batch-get-employees-by-tenant-id-request-view';

/**
 * 
 * @export
 * @interface CareworkerBatchGetEmployeesByTenantIdRequest
 */
export interface CareworkerBatchGetEmployeesByTenantIdRequest {
    /**
     * The field will contain name of the resource requested.
     * @type {Array<string>}
     * @memberof CareworkerBatchGetEmployeesByTenantIdRequest
     */
    tenantIds?: Array<string>;
    /**
     * 
     * @type {CareworkerBatchGetEmployeesByTenantIdRequestView}
     * @memberof CareworkerBatchGetEmployeesByTenantIdRequest
     */
    view?: CareworkerBatchGetEmployeesByTenantIdRequestView;
}


