/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CareworkerAccountPosition
 */
export interface CareworkerAccountPosition {
    /**
     * 
     * @type {string}
     * @memberof CareworkerAccountPosition
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerAccountPosition
     */
    accountId?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerAccountPosition
     */
    positionId?: string;
}


