/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerDictData } from './careworker-dict-data';

/**
 * 
 * @export
 * @interface CareworkerBatchUpdateDictDataSliceRequest
 */
export interface CareworkerBatchUpdateDictDataSliceRequest {
    /**
     * The DictData resource which replaces the resource on the server.
     * @type {Array<CareworkerDictData>}
     * @memberof CareworkerBatchUpdateDictDataSliceRequest
     */
    dictDataSlice?: Array<CareworkerDictData>;
    /**
     * 
     * @type {string}
     * @memberof CareworkerBatchUpdateDictDataSliceRequest
     */
    updateMask?: string;
}


