/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerBatchGetAccountsByNameRequestView } from './careworker-batch-get-accounts-by-name-request-view';

/**
 * 
 * @export
 * @interface CareworkerBatchGetAccountsByNameRequest
 */
export interface CareworkerBatchGetAccountsByNameRequest {
    /**
     * The field will contain name of the resource requested.
     * @type {Array<string>}
     * @memberof CareworkerBatchGetAccountsByNameRequest
     */
    names?: Array<string>;
    /**
     * 
     * @type {CareworkerBatchGetAccountsByNameRequestView}
     * @memberof CareworkerBatchGetAccountsByNameRequest
     */
    view?: CareworkerBatchGetAccountsByNameRequestView;
}


