/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */
export enum CareworkerBatchGetRefundRecordsByTenantIdRequestView {
    ViewUnspecified = 'VIEW_UNSPECIFIED',
    Basic = 'BASIC',
    WithEdges = 'WITH_EDGES'
}



