/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerEmployee } from './careworker-employee';

/**
 * 
 * @export
 * @interface CareworkerBatchUpdateEmployeesResponse
 */
export interface CareworkerBatchUpdateEmployeesResponse {
    /**
     * 
     * @type {Array<CareworkerEmployee>}
     * @memberof CareworkerBatchUpdateEmployeesResponse
     */
    employees?: Array<CareworkerEmployee>;
}


