/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerRole } from './careworker-role';

/**
 * 
 * @export
 * @interface CareworkerBatchCreateRolesRequest
 */
export interface CareworkerBatchCreateRolesRequest {
    /**
     * The parent resource name where the Role is to be created.
     * @type {string}
     * @memberof CareworkerBatchCreateRolesRequest
     */
    parent?: string;
    /**
     * The Role resource to create. The field name should match the Noun in the method name.
     * @type {Array<CareworkerRole>}
     * @memberof CareworkerBatchCreateRolesRequest
     */
    roles?: Array<CareworkerRole>;
}


