/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerCustomer } from './careworker-customer';

/**
 * 
 * @export
 * @interface CareworkerBatchUpdateCustomersRequest
 */
export interface CareworkerBatchUpdateCustomersRequest {
    /**
     * The Customer resource which replaces the resource on the server.
     * @type {Array<CareworkerCustomer>}
     * @memberof CareworkerBatchUpdateCustomersRequest
     */
    customers?: Array<CareworkerCustomer>;
    /**
     * 
     * @type {string}
     * @memberof CareworkerBatchUpdateCustomersRequest
     */
    updateMask?: string;
}


