/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerEmployee } from './careworker-employee';

/**
 * 
 * @export
 * @interface CareworkerBatchCreateEmployeesRequest
 */
export interface CareworkerBatchCreateEmployeesRequest {
    /**
     * The parent resource name where the Employee is to be created.
     * @type {string}
     * @memberof CareworkerBatchCreateEmployeesRequest
     */
    parent?: string;
    /**
     * The Employee resource to create. The field name should match the Noun in the method name.
     * @type {Array<CareworkerEmployee>}
     * @memberof CareworkerBatchCreateEmployeesRequest
     */
    employees?: Array<CareworkerEmployee>;
}


