/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CareworkerNoticeRecord
 */
export interface CareworkerNoticeRecord {
    /**
     * 
     * @type {string}
     * @memberof CareworkerNoticeRecord
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerNoticeRecord
     */
    tenantId?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerNoticeRecord
     */
    employeeId?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerNoticeRecord
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerNoticeRecord
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerNoticeRecord
     */
    sceneId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CareworkerNoticeRecord
     */
    read?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CareworkerNoticeRecord
     */
    recipient?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CareworkerNoticeRecord
     */
    sendType?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CareworkerNoticeRecord
     */
    noticeType?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CareworkerNoticeRecord
     */
    extra?: string;
    /**
     * 
     * @type {number}
     * @memberof CareworkerNoticeRecord
     */
    createAt?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerNoticeRecord
     */
    updateAt?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerNoticeRecord
     */
    deleteAt?: number;
}


