/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerBed } from './careworker-bed';

/**
 * 
 * @export
 * @interface CareworkerBatchUpdateBedsRequest
 */
export interface CareworkerBatchUpdateBedsRequest {
    /**
     * The Bed resource which replaces the resource on the server.
     * @type {Array<CareworkerBed>}
     * @memberof CareworkerBatchUpdateBedsRequest
     */
    beds?: Array<CareworkerBed>;
    /**
     * 
     * @type {string}
     * @memberof CareworkerBatchUpdateBedsRequest
     */
    updateMask?: string;
}


