/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerPosition } from './careworker-position';

/**
 * 
 * @export
 * @interface CareworkerListPositionsResponse
 */
export interface CareworkerListPositionsResponse {
    /**
     * The field name should match the noun \"Position\" in the method name. There will be a maximum number of items returned based on the page_size field in the request.
     * @type {Array<CareworkerPosition>}
     * @memberof CareworkerListPositionsResponse
     */
    positions?: Array<CareworkerPosition>;
    /**
     * Token to retrieve the next page of results, or empty if there are no more results in the list.
     * @type {string}
     * @memberof CareworkerListPositionsResponse
     */
    nextPageToken?: string;
}


