/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerAccountRole } from './careworker-account-role';

/**
 * 
 * @export
 * @interface CareworkerBatchCreateAccountRolesRequest
 */
export interface CareworkerBatchCreateAccountRolesRequest {
    /**
     * The parent resource name where the AccountRole is to be created.
     * @type {string}
     * @memberof CareworkerBatchCreateAccountRolesRequest
     */
    parent?: string;
    /**
     * The AccountRole resource to create. The field name should match the Noun in the method name.
     * @type {Array<CareworkerAccountRole>}
     * @memberof CareworkerBatchCreateAccountRolesRequest
     */
    accountRoles?: Array<CareworkerAccountRole>;
}


