/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerProject } from './careworker-project';

/**
 * 
 * @export
 * @interface CareworkerBatchCreateProjectsRequest
 */
export interface CareworkerBatchCreateProjectsRequest {
    /**
     * The parent resource name where the Project is to be created.
     * @type {string}
     * @memberof CareworkerBatchCreateProjectsRequest
     */
    parent?: string;
    /**
     * The Project resource to create. The field name should match the Noun in the method name.
     * @type {Array<CareworkerProject>}
     * @memberof CareworkerBatchCreateProjectsRequest
     */
    projects?: Array<CareworkerProject>;
}


