/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerNoticeSetting } from './careworker-notice-setting';

/**
 * 
 * @export
 * @interface CareworkerBatchCreateNoticeSettingsRequest
 */
export interface CareworkerBatchCreateNoticeSettingsRequest {
    /**
     * The parent resource name where the NoticeSetting is to be created.
     * @type {string}
     * @memberof CareworkerBatchCreateNoticeSettingsRequest
     */
    parent?: string;
    /**
     * The NoticeSetting resource to create. The field name should match the Noun in the method name.
     * @type {Array<CareworkerNoticeSetting>}
     * @memberof CareworkerBatchCreateNoticeSettingsRequest
     */
    noticeSettings?: Array<CareworkerNoticeSetting>;
}


