/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CareworkerRechargeOrder
 */
export interface CareworkerRechargeOrder {
    /**
     * 
     * @type {string}
     * @memberof CareworkerRechargeOrder
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerRechargeOrder
     */
    tenantId?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerRechargeOrder
     */
    sn?: string;
    /**
     * 
     * @type {number}
     * @memberof CareworkerRechargeOrder
     */
    customerId?: number;
    /**
     * 
     * @type {string}
     * @memberof CareworkerRechargeOrder
     */
    paySn?: string;
    /**
     * 
     * @type {number}
     * @memberof CareworkerRechargeOrder
     */
    payWay?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CareworkerRechargeOrder
     */
    payStatus?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CareworkerRechargeOrder
     */
    payAt?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerRechargeOrder
     */
    orderAmount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CareworkerRechargeOrder
     */
    orderTerminal?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CareworkerRechargeOrder
     */
    transactionId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CareworkerRechargeOrder
     */
    refundStatus?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CareworkerRechargeOrder
     */
    createAt?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerRechargeOrder
     */
    updateAt?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerRechargeOrder
     */
    deleteAt?: number;
}


