/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerAccount } from './careworker-account';

/**
 * 
 * @export
 * @interface CareworkerBatchCreateAccountsRequest
 */
export interface CareworkerBatchCreateAccountsRequest {
    /**
     * The parent resource name where the Account is to be created.
     * @type {string}
     * @memberof CareworkerBatchCreateAccountsRequest
     */
    parent?: string;
    /**
     * The Account resource to create. The field name should match the Noun in the method name.
     * @type {Array<CareworkerAccount>}
     * @memberof CareworkerBatchCreateAccountsRequest
     */
    accounts?: Array<CareworkerAccount>;
}


