/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerSmsLog } from './careworker-sms-log';

/**
 * 
 * @export
 * @interface CareworkerBatchUpdateSmsLogsResponse
 */
export interface CareworkerBatchUpdateSmsLogsResponse {
    /**
     * 
     * @type {Array<CareworkerSmsLog>}
     * @memberof CareworkerBatchUpdateSmsLogsResponse
     */
    smsLogs?: Array<CareworkerSmsLog>;
}


