/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CareworkerRefundLog
 */
export interface CareworkerRefundLog {
    /**
     * 
     * @type {string}
     * @memberof CareworkerRefundLog
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerRefundLog
     */
    tenantId?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerRefundLog
     */
    sn?: string;
    /**
     * 
     * @type {number}
     * @memberof CareworkerRefundLog
     */
    recordId?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerRefundLog
     */
    customerId?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerRefundLog
     */
    handleId?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerRefundLog
     */
    orderAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerRefundLog
     */
    refundAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerRefundLog
     */
    refundStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof CareworkerRefundLog
     */
    refundMsg?: string;
    /**
     * 
     * @type {number}
     * @memberof CareworkerRefundLog
     */
    createAt?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerRefundLog
     */
    updateAt?: number;
}


