/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerBatchGetCustomersByNameRequestView } from './careworker-batch-get-customers-by-name-request-view';

/**
 * 
 * @export
 * @interface CareworkerBatchGetCustomersByNameRequest
 */
export interface CareworkerBatchGetCustomersByNameRequest {
    /**
     * The field will contain name of the resource requested.
     * @type {Array<string>}
     * @memberof CareworkerBatchGetCustomersByNameRequest
     */
    names?: Array<string>;
    /**
     * 
     * @type {CareworkerBatchGetCustomersByNameRequestView}
     * @memberof CareworkerBatchGetCustomersByNameRequest
     */
    view?: CareworkerBatchGetCustomersByNameRequestView;
}


