/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerDepartment } from './careworker-department';

/**
 * 
 * @export
 * @interface CareworkerBatchGetDepartmentsResponse
 */
export interface CareworkerBatchGetDepartmentsResponse {
    /**
     * 
     * @type {Array<CareworkerDepartment>}
     * @memberof CareworkerBatchGetDepartmentsResponse
     */
    departments?: Array<CareworkerDepartment>;
}


