/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerTenant } from './careworker-tenant';

/**
 * 
 * @export
 * @interface CareworkerBatchCreateTenantsRequest
 */
export interface CareworkerBatchCreateTenantsRequest {
    /**
     * The parent resource name where the Tenant is to be created.
     * @type {string}
     * @memberof CareworkerBatchCreateTenantsRequest
     */
    parent?: string;
    /**
     * The Tenant resource to create. The field name should match the Noun in the method name.
     * @type {Array<CareworkerTenant>}
     * @memberof CareworkerBatchCreateTenantsRequest
     */
    tenants?: Array<CareworkerTenant>;
}


