/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CareworkerAccount
 */
export interface CareworkerAccount {
    /**
     * 
     * @type {string}
     * @memberof CareworkerAccount
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerAccount
     */
    tenantId?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerAccount
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerAccount
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerAccount
     */
    mobile?: string;
    /**
     * 
     * @type {number}
     * @memberof CareworkerAccount
     */
    root?: number;
    /**
     * 
     * @type {string}
     * @memberof CareworkerAccount
     */
    avatar?: string;
    /**
     * 
     * @type {number}
     * @memberof CareworkerAccount
     */
    loginTime?: number;
    /**
     * 
     * @type {string}
     * @memberof CareworkerAccount
     */
    loginIp?: string;
    /**
     * 
     * @type {number}
     * @memberof CareworkerAccount
     */
    multipointLogin?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerAccount
     */
    disable?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerAccount
     */
    createTime?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerAccount
     */
    updateTime?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerAccount
     */
    deleteTime?: number;
}


