/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerMenu } from './careworker-menu';

/**
 * 
 * @export
 * @interface CareworkerBatchUpdateMenusRequest
 */
export interface CareworkerBatchUpdateMenusRequest {
    /**
     * The Menu resource which replaces the resource on the server.
     * @type {Array<CareworkerMenu>}
     * @memberof CareworkerBatchUpdateMenusRequest
     */
    menus?: Array<CareworkerMenu>;
    /**
     * 
     * @type {string}
     * @memberof CareworkerBatchUpdateMenusRequest
     */
    updateMask?: string;
}


