/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerBatchGetAccountRolesByAccountIdRequestView } from './careworker-batch-get-account-roles-by-account-id-request-view';

/**
 * 
 * @export
 * @interface CareworkerBatchGetAccountRolesByAccountIdRequest
 */
export interface CareworkerBatchGetAccountRolesByAccountIdRequest {
    /**
     * The field will contain name of the resource requested.
     * @type {Array<string>}
     * @memberof CareworkerBatchGetAccountRolesByAccountIdRequest
     */
    accountIds?: Array<string>;
    /**
     * 
     * @type {CareworkerBatchGetAccountRolesByAccountIdRequestView}
     * @memberof CareworkerBatchGetAccountRolesByAccountIdRequest
     */
    view?: CareworkerBatchGetAccountRolesByAccountIdRequestView;
}


