/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerRefundLog } from './careworker-refund-log';

/**
 * 
 * @export
 * @interface CareworkerBatchCreateRefundLogsRequest
 */
export interface CareworkerBatchCreateRefundLogsRequest {
    /**
     * The parent resource name where the RefundLog is to be created.
     * @type {string}
     * @memberof CareworkerBatchCreateRefundLogsRequest
     */
    parent?: string;
    /**
     * The RefundLog resource to create. The field name should match the Noun in the method name.
     * @type {Array<CareworkerRefundLog>}
     * @memberof CareworkerBatchCreateRefundLogsRequest
     */
    refundLogs?: Array<CareworkerRefundLog>;
}


