/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerAccountDepartment } from './careworker-account-department';

/**
 * 
 * @export
 * @interface CareworkerBatchCreateAccountDepartmentsResponse
 */
export interface CareworkerBatchCreateAccountDepartmentsResponse {
    /**
     * 
     * @type {Array<CareworkerAccountDepartment>}
     * @memberof CareworkerBatchCreateAccountDepartmentsResponse
     */
    accountDepartments?: Array<CareworkerAccountDepartment>;
}


