/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CareworkerBatchDeleteEmployeesRequest
 */
export interface CareworkerBatchDeleteEmployeesRequest {
    /**
     * The resource id of the Employee to be deleted.
     * @type {Array<string>}
     * @memberof CareworkerBatchDeleteEmployeesRequest
     */
    ids?: Array<string>;
}


