/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerBatchGetCustomersBySnRequestView } from './careworker-batch-get-customers-by-sn-request-view';

/**
 * 
 * @export
 * @interface CareworkerBatchGetCustomersBySnRequest
 */
export interface CareworkerBatchGetCustomersBySnRequest {
    /**
     * The field will contain name of the resource requested.
     * @type {Array<string>}
     * @memberof CareworkerBatchGetCustomersBySnRequest
     */
    sns?: Array<string>;
    /**
     * 
     * @type {CareworkerBatchGetCustomersBySnRequestView}
     * @memberof CareworkerBatchGetCustomersBySnRequest
     */
    view?: CareworkerBatchGetCustomersBySnRequestView;
}


