/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CareworkerFile
 */
export interface CareworkerFile {
    /**
     * 
     * @type {string}
     * @memberof CareworkerFile
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerFile
     */
    tenantId?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerFile
     */
    cid?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerFile
     */
    sourceId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CareworkerFile
     */
    source?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CareworkerFile
     */
    type?: number;
    /**
     * 
     * @type {string}
     * @memberof CareworkerFile
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerFile
     */
    uri?: string;
    /**
     * 
     * @type {number}
     * @memberof CareworkerFile
     */
    createAt?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerFile
     */
    updateAt?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerFile
     */
    deleteAt?: number;
}


