/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerDictData } from './careworker-dict-data';

/**
 * 
 * @export
 * @interface CareworkerBatchCreateDictDataSliceRequest
 */
export interface CareworkerBatchCreateDictDataSliceRequest {
    /**
     * The parent resource name where the DictData is to be created.
     * @type {string}
     * @memberof CareworkerBatchCreateDictDataSliceRequest
     */
    parent?: string;
    /**
     * The DictData resource to create. The field name should match the Noun in the method name.
     * @type {Array<CareworkerDictData>}
     * @memberof CareworkerBatchCreateDictDataSliceRequest
     */
    dictDataSlice?: Array<CareworkerDictData>;
}


