/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerRoleMenu } from './careworker-role-menu';

/**
 * 
 * @export
 * @interface CareworkerBatchUpdateRoleMenusRequest
 */
export interface CareworkerBatchUpdateRoleMenusRequest {
    /**
     * The RoleMenu resource which replaces the resource on the server.
     * @type {Array<CareworkerRoleMenu>}
     * @memberof CareworkerBatchUpdateRoleMenusRequest
     */
    roleMenus?: Array<CareworkerRoleMenu>;
    /**
     * 
     * @type {string}
     * @memberof CareworkerBatchUpdateRoleMenusRequest
     */
    updateMask?: string;
}


