/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerAccountSession } from './careworker-account-session';

/**
 * 
 * @export
 * @interface CareworkerBatchCreateAccountSessionsRequest
 */
export interface CareworkerBatchCreateAccountSessionsRequest {
    /**
     * The parent resource name where the AccountSession is to be created.
     * @type {string}
     * @memberof CareworkerBatchCreateAccountSessionsRequest
     */
    parent?: string;
    /**
     * The AccountSession resource to create. The field name should match the Noun in the method name.
     * @type {Array<CareworkerAccountSession>}
     * @memberof CareworkerBatchCreateAccountSessionsRequest
     */
    accountSessions?: Array<CareworkerAccountSession>;
}


