/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CareworkerCustomer
 */
export interface CareworkerCustomer {
    /**
     * 
     * @type {string}
     * @memberof CareworkerCustomer
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerCustomer
     */
    tenantId?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerCustomer
     */
    sn?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerCustomer
     */
    avatar?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerCustomer
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerCustomer
     */
    realName?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerCustomer
     */
    nickname?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerCustomer
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerCustomer
     */
    mobile?: string;
    /**
     * 
     * @type {number}
     * @memberof CareworkerCustomer
     */
    sex?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerCustomer
     */
    channel?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerCustomer
     */
    isDisable?: number;
    /**
     * 
     * @type {string}
     * @memberof CareworkerCustomer
     */
    loginIp?: string;
    /**
     * 
     * @type {number}
     * @memberof CareworkerCustomer
     */
    loginAt?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CareworkerCustomer
     */
    isNewUser?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CareworkerCustomer
     */
    balance?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerCustomer
     */
    totalRechargeAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerCustomer
     */
    createAt?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerCustomer
     */
    updateAt?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerCustomer
     */
    deleteAt?: number;
}


