/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerFile } from './careworker-file';

/**
 * 
 * @export
 * @interface CareworkerBatchCreateFilesRequest
 */
export interface CareworkerBatchCreateFilesRequest {
    /**
     * The parent resource name where the File is to be created.
     * @type {string}
     * @memberof CareworkerBatchCreateFilesRequest
     */
    parent?: string;
    /**
     * The File resource to create. The field name should match the Noun in the method name.
     * @type {Array<CareworkerFile>}
     * @memberof CareworkerBatchCreateFilesRequest
     */
    files?: Array<CareworkerFile>;
}


