/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerRechargeOrder } from './careworker-recharge-order';

/**
 * 
 * @export
 * @interface CareworkerBatchCreateRechargeOrdersRequest
 */
export interface CareworkerBatchCreateRechargeOrdersRequest {
    /**
     * The parent resource name where the RechargeOrder is to be created.
     * @type {string}
     * @memberof CareworkerBatchCreateRechargeOrdersRequest
     */
    parent?: string;
    /**
     * The RechargeOrder resource to create. The field name should match the Noun in the method name.
     * @type {Array<CareworkerRechargeOrder>}
     * @memberof CareworkerBatchCreateRechargeOrdersRequest
     */
    rechargeOrders?: Array<CareworkerRechargeOrder>;
}


