/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerDictType } from './careworker-dict-type';

/**
 * 
 * @export
 * @interface CareworkerBatchCreateDictTypesRequest
 */
export interface CareworkerBatchCreateDictTypesRequest {
    /**
     * The parent resource name where the DictType is to be created.
     * @type {string}
     * @memberof CareworkerBatchCreateDictTypesRequest
     */
    parent?: string;
    /**
     * The DictType resource to create. The field name should match the Noun in the method name.
     * @type {Array<CareworkerDictType>}
     * @memberof CareworkerBatchCreateDictTypesRequest
     */
    dictTypes?: Array<CareworkerDictType>;
}


