/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CareworkerNoticeSetting
 */
export interface CareworkerNoticeSetting {
    /**
     * 
     * @type {string}
     * @memberof CareworkerNoticeSetting
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerNoticeSetting
     */
    tenantId?: string;
    /**
     * 
     * @type {number}
     * @memberof CareworkerNoticeSetting
     */
    sceneId?: number;
    /**
     * 
     * @type {string}
     * @memberof CareworkerNoticeSetting
     */
    sceneName?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerNoticeSetting
     */
    sceneDesc?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CareworkerNoticeSetting
     */
    recipient?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CareworkerNoticeSetting
     */
    type?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CareworkerNoticeSetting
     */
    systemNotice?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerNoticeSetting
     */
    smsNotice?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerNoticeSetting
     */
    oaNotice?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerNoticeSetting
     */
    mnpNotice?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerNoticeSetting
     */
    support?: string;
    /**
     * 
     * @type {number}
     * @memberof CareworkerNoticeSetting
     */
    updateAt?: number;
}


