/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerBatchGetAccountSessionsByAccountIdRequestView } from './careworker-batch-get-account-sessions-by-account-id-request-view';

/**
 * 
 * @export
 * @interface CareworkerBatchGetAccountSessionsByAccountIdRequest
 */
export interface CareworkerBatchGetAccountSessionsByAccountIdRequest {
    /**
     * The field will contain name of the resource requested.
     * @type {Array<number>}
     * @memberof CareworkerBatchGetAccountSessionsByAccountIdRequest
     */
    accountIds?: Array<number>;
    /**
     * 
     * @type {CareworkerBatchGetAccountSessionsByAccountIdRequestView}
     * @memberof CareworkerBatchGetAccountSessionsByAccountIdRequest
     */
    view?: CareworkerBatchGetAccountSessionsByAccountIdRequestView;
}


