/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CareworkerTenant
 */
export interface CareworkerTenant {
    /**
     * 
     * @type {string}
     * @memberof CareworkerTenant
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerTenant
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerTenant
     */
    remark?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerTenant
     */
    license?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerTenant
     */
    contract?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerTenant
     */
    phone?: string;
    /**
     * 
     * @type {number}
     * @memberof CareworkerTenant
     */
    createTime?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerTenant
     */
    updateTime?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerTenant
     */
    deleteTime?: number;
}


