/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CareworkerSmsLog
 */
export interface CareworkerSmsLog {
    /**
     * 
     * @type {string}
     * @memberof CareworkerSmsLog
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerSmsLog
     */
    tenantId?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerSmsLog
     */
    sceneId?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerSmsLog
     */
    mobile?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerSmsLog
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerSmsLog
     */
    code?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CareworkerSmsLog
     */
    isVerify?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CareworkerSmsLog
     */
    checkNum?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CareworkerSmsLog
     */
    sendStatus?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CareworkerSmsLog
     */
    sendAt?: number;
    /**
     * 
     * @type {string}
     * @memberof CareworkerSmsLog
     */
    results?: string;
    /**
     * 
     * @type {number}
     * @memberof CareworkerSmsLog
     */
    createAt?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerSmsLog
     */
    updateAt?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerSmsLog
     */
    deleteAt?: number;
}


