/* tslint:disable */
/* eslint-disable */
/**
 * server/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerPosition } from './careworker-position';

/**
 * 
 * @export
 * @interface CareworkerBatchCreatePositionsRequest
 */
export interface CareworkerBatchCreatePositionsRequest {
    /**
     * The parent resource name where the Position is to be created.
     * @type {string}
     * @memberof CareworkerBatchCreatePositionsRequest
     */
    parent?: string;
    /**
     * The Position resource to create. The field name should match the Noun in the method name.
     * @type {Array<CareworkerPosition>}
     * @memberof CareworkerBatchCreatePositionsRequest
     */
    positions?: Array<CareworkerPosition>;
}


