/* tslint:disable */
/* eslint-disable */
/**
 * agg/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CareworkerEmployee } from './careworker-employee';
import { CareworkerMenuTree } from './careworker-menu-tree';

/**
 * 
 * @export
 * @interface CareworkerCurrentResponse
 */
export interface CareworkerCurrentResponse {
    /**
     * 
     * @type {CareworkerEmployee}
     * @memberof CareworkerCurrentResponse
     */
    userInfo?: CareworkerEmployee;
    /**
     * 
     * @type {Array<CareworkerMenuTree>}
     * @memberof CareworkerCurrentResponse
     */
    menus?: Array<CareworkerMenuTree>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CareworkerCurrentResponse
     */
    permissions?: Array<string>;
}


