/* tslint:disable */
/* eslint-disable */
/**
 * agg/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CareworkerMenu
 */
export interface CareworkerMenu {
    /**
     * 
     * @type {string}
     * @memberof CareworkerMenu
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerMenu
     */
    pid?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerMenu
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerMenu
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerMenu
     */
    icon?: string;
    /**
     * 
     * @type {number}
     * @memberof CareworkerMenu
     */
    order?: number;
    /**
     * 
     * @type {string}
     * @memberof CareworkerMenu
     */
    perms?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerMenu
     */
    paths?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerMenu
     */
    component?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerMenu
     */
    selected?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerMenu
     */
    params?: string;
    /**
     * 
     * @type {number}
     * @memberof CareworkerMenu
     */
    isCache?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerMenu
     */
    hidden?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerMenu
     */
    isDisable?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerMenu
     */
    createAt?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerMenu
     */
    updateAt?: number;
}


