/* tslint:disable */
/* eslint-disable */
/**
 * agg/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CareworkerEmployee
 */
export interface CareworkerEmployee {
    /**
     * 
     * @type {string}
     * @memberof CareworkerEmployee
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerEmployee
     */
    tenantId?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerEmployee
     */
    avatar?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerEmployee
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerEmployee
     */
    realName?: string;
    /**
     * 
     * @type {string}
     * @memberof CareworkerEmployee
     */
    mobile?: string;
    /**
     * 
     * @type {number}
     * @memberof CareworkerEmployee
     */
    sex?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerEmployee
     */
    age?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerEmployee
     */
    language?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerEmployee
     */
    isDisable?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerEmployee
     */
    createAt?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerEmployee
     */
    updateAt?: number;
    /**
     * 
     * @type {number}
     * @memberof CareworkerEmployee
     */
    deleteAt?: number;
}


