/* tslint:disable */
/* eslint-disable */
/**
 * agg/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CareworkerConfigsResponse
 */
export interface CareworkerConfigsResponse {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CareworkerConfigsResponse
     */
    configs?: { [key: string]: string; };
}


