/* tslint:disable */
/* eslint-disable */
/**
 * agg/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CareworkerConfigsResponse } from '../models';
// @ts-ignore
import { CareworkerCurrentResponse } from '../models';
// @ts-ignore
import { CareworkerLoginRequest } from '../models';
// @ts-ignore
import { CareworkerLoginResponse } from '../models';
// @ts-ignore
import { CareworkerLogoutRequest } from '../models';
// @ts-ignore
import { RpcStatus } from '../models';
/**
 * AggServiceApi - axios parameter creator
 * @export
 */
export const AggServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aggServiceConfigs: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/configs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aggServiceCurrent: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/auth/current`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CareworkerLoginRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aggServiceLogin: async (body: CareworkerLoginRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling aggServiceLogin.');
            }
            const localVarPath = `/api/v1/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const nonString = typeof body !== 'string';
            const needsSerialization = nonString && configuration && configuration.isJsonMime
                ? configuration.isJsonMime(localVarRequestOptions.headers['Content-Type'])
                : nonString;
            localVarRequestOptions.data =  needsSerialization
                ? JSON.stringify(body !== undefined ? body : {})
                : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CareworkerLogoutRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aggServiceLogout: async (body: CareworkerLogoutRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling aggServiceLogout.');
            }
            const localVarPath = `/api/v1/auth/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const nonString = typeof body !== 'string';
            const needsSerialization = nonString && configuration && configuration.isJsonMime
                ? configuration.isJsonMime(localVarRequestOptions.headers['Content-Type'])
                : nonString;
            localVarRequestOptions.data =  needsSerialization
                ? JSON.stringify(body !== undefined ? body : {})
                : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AggServiceApi - functional programming interface
 * @export
 */
export const AggServiceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async aggServiceConfigs(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CareworkerConfigsResponse>> {
            const localVarAxiosArgs = await AggServiceApiAxiosParamCreator(configuration).aggServiceConfigs(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async aggServiceCurrent(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CareworkerCurrentResponse>> {
            const localVarAxiosArgs = await AggServiceApiAxiosParamCreator(configuration).aggServiceCurrent(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {CareworkerLoginRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async aggServiceLogin(body: CareworkerLoginRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CareworkerLoginResponse>> {
            const localVarAxiosArgs = await AggServiceApiAxiosParamCreator(configuration).aggServiceLogin(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {CareworkerLogoutRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async aggServiceLogout(body: CareworkerLogoutRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await AggServiceApiAxiosParamCreator(configuration).aggServiceLogout(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AggServiceApi - factory interface
 * @export
 */
export const AggServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aggServiceConfigs(options?: any): AxiosPromise<CareworkerConfigsResponse> {
            return AggServiceApiFp(configuration).aggServiceConfigs(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aggServiceCurrent(options?: any): AxiosPromise<CareworkerCurrentResponse> {
            return AggServiceApiFp(configuration).aggServiceCurrent(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CareworkerLoginRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aggServiceLogin(body: CareworkerLoginRequest, options?: any): AxiosPromise<CareworkerLoginResponse> {
            return AggServiceApiFp(configuration).aggServiceLogin(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CareworkerLogoutRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aggServiceLogout(body: CareworkerLogoutRequest, options?: any): AxiosPromise<object> {
            return AggServiceApiFp(configuration).aggServiceLogout(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AggServiceApi - object-oriented interface
 * @export
 * @class AggServiceApi
 * @extends {BaseAPI}
 */
export class AggServiceApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AggServiceApi
     */
    public aggServiceConfigs(options?: any) {
        return AggServiceApiFp(this.configuration).aggServiceConfigs(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AggServiceApi
     */
    public aggServiceCurrent(options?: any) {
        return AggServiceApiFp(this.configuration).aggServiceCurrent(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CareworkerLoginRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AggServiceApi
     */
    public aggServiceLogin(body: CareworkerLoginRequest, options?: any) {
        return AggServiceApiFp(this.configuration).aggServiceLogin(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CareworkerLogoutRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AggServiceApi
     */
    public aggServiceLogout(body: CareworkerLogoutRequest, options?: any) {
        return AggServiceApiFp(this.configuration).aggServiceLogout(body, options).then((request) => request(this.axios, this.basePath));
    }
}
